datasetPath: /home/constantin/Doctorat/YoloModels/YoloLib2/Utils/YAMLconfigs/coco.yaml
#datasetPath: /home/constantin/Doctorat/FireDataset/RoboflowDS/yolov8/data.yaml
#testVideosPath: /home/constantin/Doctorat/FireDataset/VideoTestFire/FireDay/
#testVideosPath: /home/constantin/Doctorat/FireDataset/VideoTestFire/FireDay/
testVideosPath: /home/constantin/Doctorat/YoloModels/testVideos